// Generated by CoffeeScript 1.6.3
(function() {
  var emysql;

  emysql = require('../index');

  emysql.init(__dirname + '/config.json');

  emysql.conn.query('SHOW DATABASES;', function(err, rows) {
    if (err != null) {
      throw err;
    }
    return console.log("Show databases: " + (JSON.stringify(rows)));
  });

}).call(this);
