// Generated by CoffeeScript 1.6.3
(function() {
  var belog, emysql;

  emysql = require('../index');

  emysql.init(__dirname + '/config.json');

  belog = function(cb) {
    return function(err, rows) {
      if (err != null) {
        conosle.log("Error Occured: " + (JSON.stringify(err, null, '\t')));
      }
      console.log("Data Retrived: " + (JSON.stringify(rows, null, '\t')));
      if (typeof cb === 'function') {
        return cb();
      }
    };
  };

  emysql.conn.query('SHOW DATABASES;', belog());

  emysql.conn.query('CREATE TABLE test (id INT NOT NULL,data TEXT NOT NULL,PRIMARY KEY (id))', belog(function() {
    setInterval(function() {
      return emysql.conn.query('INSERT INTO test SET data = ?;', ['test_data,lalala']);
    }, 3000);
    return setInterval(function() {
      return emysql.conn.query('SELECT * FROM test LIMIT 20;', belog());
    }, 1000);
  }));

  setTimeout(function() {
    console.log(' ============ Pool will be killed after 3 minutes ===========');
    return process.exit(0);
  }, 180000);

}).call(this);
